//
// Created by laci200270 on 2018.01.13..
//

#ifndef JEDLIKGAME_CONFIGS_H
#define JEDLIKGAME_CONFIGS_H
#define WIDTH 1200
#define HEIGHT 700
#define SCALING_W 2
#define SCALING_H 2
#define MOVINGSPEEDX 8
#define DBG_TEXTURES 0
#define DBG_USELESS_MOVING_LOGS 1
#endif //JEDLIKGAME_CONFIGS_H
